
[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enhanced CORS and cache control headers
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Clear-Site-Data = "\"cache\", \"cookies\", \"storage\""
    X-Content-Type-Options = "nosniff"
    Pragma = "no-cache"
    Expires = "0"

# Add versioning to assets
[[headers]]
  for = "*.js"
    [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "*.css"
    [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "*.html"
    [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"

# Force cache invalidation with timestamp
[build.environment]
  NETLIFY_FORCE_NEW_BUILD = "true"
  NETLIFY_CACHE_BUST = "${COMMIT_REF}-${DEPLOY_PRIME_URL}-${RANDOM}"
  BUILD_TIMESTAMP = "${TIMESTAMP}-${RANDOM}"
  VITE_APP_BUILD_TIME = "${TIMESTAMP}"
  VITE_APP_RANDOM_VERSION = "${RANDOM}"
